org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 4
      delete_succeeded_jobs_after: 1 #succeeded jobs will go to the deleted state after 1 hour
    dashboard:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jobrunr
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD}