org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 4
    dashboard:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jobrunr
    username: ${MY_SQL_USER}
    password: ${MY_SQL_PASSWORD}
